-- +goose Up
CREATE TABLE IF NOT EXISTS ke_dataconex (
  ked_codigo VARCHAR(6) NOT NULL,
  ked_nombre VARCHAR(80) NOT NULL DEFAULT '',
  ked_status BOOLEAN NOT NULL DEFAULT 0,
  ked_enlace TEXT NOT NULL,
  ked_agen VARCHAR(20) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_dataconex PRIMARY KEY (ked_codigo)
);

CREATE TABLE IF NOT EXISTS listbanc (
  codbanco SMALLINT NOT NULL,
  nombanco VARCHAR(59) NOT NULL DEFAULT '',
  cuentanac CHAR(1) NOT NULL DEFAULT '0',
  inactiva BOOLEAN NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_config PRIMARY KEY (codbanco)
);

CREATE TABLE IF NOT EXISTS ke_wcnf_conf (
  cnfg_idconfig char(30) NOT NULL,
  cnfg_clase char(1) NOT NULL DEFAULT '',
  cnfg_tipo char(1) NOT NULL,
  cnfg_valnum DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cnfg_valsino BOOLEAN NOT NULL DEFAULT 0,
  cnfg_valtxt TEXT NOT NULL,
  cnfg_lentxt SMALLINT NOT NULL DEFAULT 0,
  cnfg_valfch date NOT NULL DEFAULT '0001-01-01',
  cnfg_activa BOOLEAN NOT NULL DEFAULT 0,
  cnfg_etiq TEXT NOT NULL,
  cnfg_ttip TEXT NOT NULL,
  username varchar(30) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_config PRIMARY KEY (cnfg_idconfig, username)
);

CREATE TABLE IF NOT EXISTS grupos (
  codigo INT NOT NULL,
  nombre VARCHAR(80) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_grupos PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS subgrupos (
  codigo INT NOT NULL,
  subcodigo INT NOT NULL,
  nombre varchar(80) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_subgrupos PRIMARY KEY (codigo, subcodigo)
);

CREATE TABLE IF NOT EXISTS sectores (
  codigo INT NOT NULL,
  zona varchar(50) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_config PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS subsectores (
  codigo INT NOT NULL,
  subcodigo INT NOT NULL,
  subsector varchar(50) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_config PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS articulo (
  codigo VARCHAR(25) NOT NULL,
  grupo VARCHAR(6) NOT NULL DEFAULT '',
  subgrupo VARCHAR(6) NOT NULL DEFAULT '',
  nombre VARCHAR(150) NOT NULL DEFAULT '',
  referencia VARCHAR(20) NOT NULL DEFAULT '',
  marca VARCHAR(20) NOT NULL DEFAULT '',
  unidad VARCHAR(15) NOT NULL DEFAULT '',
  existencia INT NOT NULL DEFAULT 0,
  precio1 DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  precio2 DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  precio3 DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  precio4 DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  precio5 DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  precio6 DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  precio7 DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  discont BOOLEAN NOT NULL DEFAULT 0,
  vta_max INT NOT NULL DEFAULT 0,
  vta_min INT NOT NULL DEFAULT 0,
  dctotope DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  enpreventa BOOLEAN NOT NULL DEFAULT 0,
  comprometido INT NOT NULL DEFAULT 0,
  vta_minenx INT NOT NULL DEFAULT 0,
  vta_solofac BOOLEAN NOT NULL DEFAULT 0,
  vta_solone BOOLEAN NOT NULL DEFAULT 0,
  codbarras VARCHAR(20) NOT NULL DEFAULT '',
  detalles TEXT NOT NULL,
  cantbulto INT NOT NULL DEFAULT 0,
  costo_prom DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  util1 DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  util2 DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  util3 DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  fchultcomp DATE NOT NULL DEFAULT '0001-01-01',
  qtyultcomp INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_articulo PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS listvend (
  codigo VARCHAR(8) NOT NULL,
  nombre VARCHAR(54) DEFAULT '',
  telefonos VARCHAR(100) DEFAULT '',
  telefono_movil VARCHAR(100) DEFAULT '',
  status CHAR(1) NOT NULL DEFAULT '1',
  superves CHAR(1) NOT NULL DEFAULT '0',
  supervpor VARCHAR(8) NOT NULL DEFAULT '',
  sector VARCHAR(6) DEFAULT '',
  subcodigo VARCHAR(6) NOT NULL,
  nivgcial BOOLEAN NOT NULL DEFAULT 0,
  email TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_config PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS usuarios (
  nombre varchar(30) NOT NULL DEFAULT '',
  username varchar(30) NOT NULL DEFAULT '',
  password varchar(20) DEFAULT NULL,
  vendedor varchar(8) NOT NULL DEFAULT '',
  almacen char(2) DEFAULT '01',
  desactivo BOOLEAN NOT NULL DEFAULT 0,
  ualterprec INT NOT NULL DEFAULT 0,
  sesionactiva TIMESTAMP NOT NULL DEFAULT NOW(),
  ult_sinc TIMESTAMP NOT NULL DEFAULT NOW(),
  version varchar(30)  NOT NULL DEFAULT '0.0.0',
  sesion BOOLEAN NOT NULL DEFAULT 0,
  cierre_sesion BOOLEAN NOT NULL DEFAULT 0,
  comisiones BOOLEAN NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_config PRIMARY KEY (vendedor)
);

CREATE TABLE IF NOT EXISTS cliempre (
  codigo VARCHAR(20) NOT NULL,
  nombre VARCHAR(100) NOT NULL DEFAULT '',
  direccion VARCHAR(200) DEFAULT '',
  telefonos VARCHAR(150) DEFAULT '',
  perscont VARCHAR(50) DEFAULT '',
  vendedor VARCHAR(8) DEFAULT '',
  contribespecial BOOLEAN NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 0,
  sector VARCHAR(6) DEFAULT '',
  subcodigo VARCHAR(6) NOT NULL DEFAULT '',
  precio SMALLINT NOT NULL DEFAULT 1,
  email TEXT NOT NULL,
  kne_activa BOOLEAN NOT NULL DEFAULT 0,
  kne_mtomin DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  noemifac BOOLEAN NOT NULL DEFAULT 0,
  noeminota BOOLEAN NOT NULL DEFAULT 0,
  fchultvta DATE NOT NULL DEFAULT '0001-01-01',
  mtoultvta DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  prcdpagdia DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  promdiasp DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  riesgocrd DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  cantdocs INT NOT NULL DEFAULT 0,
  totmtodocs DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  prommtodoc DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  diasultvta DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  promdiasvta DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  limcred DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  fchcrea DATE NOT NULL DEFAULT '0001-01-01',
  dolarflete BOOLEAN NOT NULL DEFAULT 0,
  nodolarflete BOOLEAN NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_cliempre PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS ke_estadc01 (
  codcoord VARCHAR(8) NOT NULL DEFAULT '' ,
  nomcoord VARCHAR(54) NOT NULL DEFAULT '' ,
  vendedor VARCHAR(8) NOT NULL,
  nombrevend VARCHAR(54) NOT NULL DEFAULT '' ,
  cntpedidos INT NOT NULL DEFAULT 0,
  mtopedidos DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cntfacturas INT NOT NULL DEFAULT 0,
  mtofacturas DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  metavend DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  prcmeta DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cntclientes INT NOT NULL DEFAULT 0,
  clivisit INT NOT NULL DEFAULT 0,
  prcvisitas DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  lom_montovtas DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  lom_prcvtas DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  lom_prcvisit DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  rlom_montovtas DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  rlom_prcvtas DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  rlom_prcvisit DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  fecha_estad date NOT NULL DEFAULT '0001-01-01',
  ppgdol_totneto DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  devdol_totneto DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  defdol_totneto DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  totdolcob DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cntrecl DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  mtorecl DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_estad PRIMARY KEY (vendedor)
);

CREATE TABLE IF NOT EXISTS ke_opti (
  kti_ndoc varchar(17) NOT NULL,
  kti_tdoc varchar(3) NOT NULL DEFAULT '',
  kti_codcli varchar(20) NOT NULL DEFAULT '',
  kti_nombrecli varchar(100) NOT NULL DEFAULT ' ',
  kti_codven varchar(8) NOT NULL DEFAULT '',
  kti_docsol CHAR(1) NOT NULL DEFAULT '',
  kti_condicion CHAR(1) NOT NULL DEFAULT '',
  kti_tipprec CHAR(1) NOT NULL DEFAULT '0',
  kti_totneto DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  kti_status CHAR(1) NOT NULL DEFAULT '0',
  kti_nroped varchar(8) NOT NULL DEFAULT '',
  kti_fchdoc datetime NOT NULL DEFAULT '0001-01-01 01:01:01',
  kti_negesp BOOLEAN NOT NULL DEFAULT 0,
  ke_pedstatus CHAR(2) NOT NULL DEFAULT '',
  dolarflete BOOLEAN NOT NULL DEFAULT 0,
  complemento BOOLEAN NOT NULL DEFAULT 0,
  nro_complemento varchar(17) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_estad PRIMARY KEY (kti_ndoc)
);

CREATE TABLE IF NOT EXISTS ke_opmv (
  kti_tdoc VARCHAR(8) NOT NULL DEFAULT '',
  kti_ndoc VARCHAR(17) NOT NULL,
  kti_tipprec CHAR(1) NOT NULL DEFAULT '1',
  kmv_codart VARCHAR(25) NOT NULL,
  kmv_nombre VARCHAR(150) NOT NULL DEFAULT '',
  kmv_cant INT NOT NULL DEFAULT 0.00,
  kmv_artprec DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  kmv_stot DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  kmv_dctolin DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_opmv PRIMARY KEY (kti_ndoc, kmv_codart)
);

CREATE TABLE IF NOT EXISTS ke_doccti (
  agencia VARCHAR(3) NOT NULL DEFAULT '',
  tipodoc VARCHAR(3) NOT NULL DEFAULT '',
  documento VARCHAR(8) NOT NULL,
  tipodocv VARCHAR(3) NOT NULL DEFAULT '',
  codcliente VARCHAR(20) NOT NULL DEFAULT '',
  nombrecli VARCHAR(100) NOT NULL DEFAULT '',
  contribesp BOOLEAN NOT NULL DEFAULT 0,
  ruta_parme BOOLEAN NOT NULL DEFAULT 0,
  tipoprecio CHAR(1) NOT NULL DEFAULT '1',
  emision DATE NOT NULL DEFAULT '0001-01-01',
  recepcion DATE NOT NULL DEFAULT '0001-01-01',
  vence DATE NOT NULL DEFAULT '0001-01-01',
  diascred DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  estatusdoc CHAR(1) NOT NULL DEFAULT '0',
  dtotneto DECIMAL(8,4) NOT NULL DEFAULT 0.00,
  dtotimpuest DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dtotalfinal DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dtotpagos DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dtotdescuen DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dFlete DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dtotdev DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dvndmtototal DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dretencion DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dretencioniva DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  vendedor VARCHAR(8) NOT NULL DEFAULT '',
  codcoord VARCHAR(8) NOT NULL DEFAULT '',
  aceptadev BOOLEAN NOT NULL DEFAULT 1,
  kti_negesp BOOLEAN NOT NULL DEFAULT 0,
  bsiva DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  bsflete DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  bsretencion DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  bsretencioniva DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  tasadoc DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  mtodcto DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  fchvencedcto DATE NOT NULL DEFAULT '0001-01-01',
  tienedcto BOOLEAN NOT NULL DEFAULT 0,
  cbsret DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cdret DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cbsretiva DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cdretiva DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cbsrparme DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cdrparme DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cbsretflete DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  cdretflete DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  bsmtoiva DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  bsmtofte DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  retmun_mto DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dolarflete BOOLEAN NOT NULL DEFAULT 0,
  bsretflete DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dretflete DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dretmun_mto DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  retivaoblig BOOLEAN NOT NULL DEFAULT 0,
  edoentrega BOOLEAN NOT NULL DEFAULT 0,
  dmtoiva DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  prcdctoaplic DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  montodctodol DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  montodctobs DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_documento PRIMARY KEY (documento)
);

CREATE TABLE IF NOT EXISTS ke_doclmv (
  agencia VARCHAR(3) NOT NULL DEFAULT '',
  tipodoc VARCHAR(3) NOT NULL DEFAULT '',
  documento VARCHAR(8) NOT NULL,
  tipodocv VARCHAR(3) NOT NULL DEFAULT '',
  grupo VARCHAR(6) NOT NULL DEFAULT '',
  subgrupo VARCHAR(6) NOT NULL DEFAULT '',
  origen DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  codigo VARCHAR(25) NOT NULL,
  codhijo VARCHAR(25) NOT NULL DEFAULT '',
  pid VARCHAR(12) NOT NULL DEFAULT '',
  nombre VARCHAR(100) NOT NULL DEFAULT '',
  cantidad INT NOT NULL DEFAULT 0,
  cntdevuelt INT NOT NULL DEFAULT 0,
  vndcntdevuelt DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dvndmtototal DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dpreciofin DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dpreciounit DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dmontoneto DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  dmontototal DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  timpueprc DECIMAL(8, 4) NOT NULL DEFAULT 0.00,
  unidevuelt INT NOT NULL DEFAULT 0,
  fechadoc DATE NOT NULL DEFAULT '0001-01-01',
  vendedor VARCHAR(8) NOT NULL DEFAULT '',
  codcoord VARCHAR(8) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP DEFAULT NULL,
  CONSTRAINT PK_documento_lineas PRIMARY KEY (documento, codigo)
);

-- +goose Down
DROP TABLE ke_dataconex;
DROP TABLE listbanc;
DROP TABLE ke_wcnf_conf;
DROP TABLE grupos;
DROP TABLE subgrupos;
DROP TABLE sectores;
DROP TABLE subsectores;
DROP TABLE articulo;
DROP TABLE listvend;
DROP TABLE usuarios;
DROP TABLE cliempre;
DROP TABLE ke_estadc01;
DROP TABLE ke_opti;
DROP TABLE ke_opmv;
DROP TABLE ke_doccti;
DROP TABLE ke_doclmv;

