-- +goose Up
CREATE TABLE ke_doclmv (
  agencia varchar(3) NOT NULL DEFAULT '' COMMENT 'Agencia',
  tipodoc varchar(3) NOT NULL DEFAULT '' COMMENT 'Tipo de documento',
  documento varchar(8) NOT NULL DEFAULT '' COMMENT 'Numero de documento',
  tipodocv varchar(3) NOT NULL DEFAULT '' COMMENT 'Tipo de documento visual',
  grupo varchar(6) NOT NULL DEFAULT '' COMMENT 'Grupo del articulo',
  subgrupo varchar(6) NOT NULL DEFAULT '' COMMENT 'Subgrupo del articulo',
  origen decimal(2, 0) NOT NULL DEFAULT '0' COMMENT 'Origen del articulo',
  codigo varchar(25) NOT NULL DEFAULT '' COMMENT 'Código del artículo',
  codhijo varchar(25) NOT NULL DEFAULT '' COMMENT 'Código art. dependiente',
  pid varchar(12) NOT NULL DEFAULT '' COMMENT 'Id de linea',
  nombre varchar(100) NOT NULL DEFAULT ' ' COMMENT 'Nombre de articulo',
  cantidad decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Cantidad de unds',
  cntdevuelt decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Cantidad devuelta',
  vndcntdevuelt decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Cantidad dev x vendedor',
  dvndmtototal decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto total dev x vend',
  dpreciofin decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Precio final en divisas',
  dpreciounit decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Precio unitario en divisas',
  dmontoneto decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto Neto en divisas',
  dmontototal decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto total en divisas',
  timpueprc decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Tasa de IVA del artículo',
  unidevuelt decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Tasa de IVA del artículo',
  fechadoc date NOT NULL DEFAULT '0001-01-01' COMMENT 'Emision del documento',
  vendedor varchar(8) NOT NULL DEFAULT '' COMMENT 'Código del vendedor',
  codcoord varchar(8) NOT NULL DEFAULT '' COMMENT 'Código del coordinador',
  fechamodifi datetime NOT NULL DEFAULT '0001-01-01 01:01:01' COMMENT 'Ultima actualización del registro',
  CONSTRAINT PK_documento PRIMARY KEY (documento, codigo)
);

CREATE TABLE ke_doccti (
  agencia varchar(3) NOT NULL DEFAULT '' COMMENT 'Agencia',
  tipodoc varchar(3) NOT NULL DEFAULT '' COMMENT 'Tipo de documento',
  documento varchar(8) NOT NULL DEFAULT '' COMMENT 'numero de documento',
  tipodocv varchar(3) NOT NULL DEFAULT '' COMMENT 'Tipo de documento visual',
  codcliente varchar(20) NOT NULL DEFAULT '' COMMENT 'Código de cliente',
  nombrecli varchar(100) NOT NULL DEFAULT ' ' COMMENT 'Nombre de Cliente',
  contribesp decimal(4, 0) NOT NULL DEFAULT '0' COMMENT 'Contribuyente especial',
  ruta_parme char(1) NOT NULL DEFAULT '' COMMENT 'Cliente en ruta parme',
  tipoprecio decimal(2, 0) NOT NULL DEFAULT '0' COMMENT 'Tipo de precio aplicado',
  emision date NOT NULL DEFAULT '0001-01-01' COMMENT 'Emision del documento',
  recepcion date NOT NULL DEFAULT '0001-01-01' COMMENT 'recepcion de la mercancía',
  vence date NOT NULL DEFAULT '0001-01-01' COMMENT 'vencimiento del documento',
  diascred decimal(3, 0) NOT NULL DEFAULT '0' COMMENT 'días de crédito',
  estatusdoc varchar(1) NOT NULL DEFAULT '' COMMENT 'estatus del documento',
  dtotneto decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'monto neto del doc',
  dtotimpuest decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Total impuestos',
  dtotalfinal decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Total final del documento',
  dtotpagos decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Total monto pagado',
  dtotdescuen decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Total monto descuentos',
  dFlete decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto del flete incluido en doc',
  dtotdev decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto total de devoluciones',
  dvndmtototal decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto total dev x vend',
  dretencion decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto total de retenciones',
  dretencioniva decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto retencion IVA',
  vendedor varchar(8) NOT NULL DEFAULT '' COMMENT 'Código del vendedor',
  codcoord varchar(8) NOT NULL DEFAULT '' COMMENT 'Código del coordinador',
  fechamodifi datetime NOT NULL DEFAULT '0001-01-01 01:01:01' COMMENT 'Ultima actualización del registro',
  aceptadev char(1) NOT NULL DEFAULT '1' COMMENT 'si acepta dev el doc (0 = no 1= si)',
  kti_negesp char(1) NOT NULL DEFAULT '0' COMMENT 'Si posee negociación especial',
  bsiva decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'IVA del documento en bolívares',
  bsflete decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Flete del documento en bolívares	',
  bsretencion decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Retención total del documento en bolívares ?',
  bsretencioniva decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Retención del IVA del documento en bolívares ?',
  tasadoc decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Tasa del Documento cuando es facturado ?',
  mtodcto decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto de dscto aplicado en divisas',
  fchvencedcto date NOT NULL DEFAULT '0001-01-01' COMMENT 'Fecha hasta la cual estará en vigencia el descuento',
  tienedcto char(1) NOT NULL DEFAULT '0' COMMENT 'Edo del dcto (0=vigente,1=Por aplicar, 2=aplicado, 3=Vencido o Anulado)',
  cbsret decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Lo que hay que cobrar en total de las retenciones del documento en bolívares',
  cdret decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Lo que hay que cobrar en total de las retenciones del documento en dólares',
  cbsretiva decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Lo que hay que cobrar de la retención del IVA en bolívares',
  cdretiva decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Lo que hay que cobrar de la retención del IVA en dólares',
  cbsrparme decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Lo que hay que cobrar de la retención del PARME en bolívares',
  cdrparme decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Lo que hay que cobrar de la retención del PARME en dólares',
  cbsretflete decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Lo que hay que cobrar de la de la retención del Flete en bolívares',
  cdretflete decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Lo que hay que cobrar de la retención del Flete en dólares',
  bsmtoiva decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Cobrado del IVA en bolívares',
  bsmtofte decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Cobrado del Flete en bolívares',
  retmun_mto decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Parme cobrado del documento en bolívares bs',
  dolarflete int NOT NULL DEFAULT '0' COMMENT 'Documento con flete dolarizado 0 = no, 1 = si',
  bsretflete decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Lo cobrado de la retención de flete en bolívares BS',
  dretflete decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Lo cobrado de la retención de flete en dólares $',
  dretmun_mto decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Parme cobrado del documento en dólares $',
  retivaoblig tinyint (1) NOT NULL DEFAULT '0' COMMENT 'Retención de IVA Obligatoria',
  edoentrega tinyint (1) NOT NULL DEFAULT '0' COMMENT '0 = Facturado,\r\n1 = En tránsito,\r\n2 = Entregado',
  dmtoiva decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Moto cobrando del IVA en divisas',
  prcdctoaplic decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT '% Dcto a aplicado',
  montodctodol decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto del dcto en $',
  montodctobs decimal(24, 7) NOT NULL DEFAULT '0.0000000' COMMENT 'Monto del dcto en Bs',
  CONSTRAINT PK_documento PRIMARY KEY (documento)
);

CREATE TABLE IF NOT EXISTS ke_dataconex (
  ked_codigo VARCHAR(6) NOT NULL PRIMARY KEY,
  ked_nombre VARCHAR(80) NOT NULL,
  ked_status INT NOT NULL DEFAULT 0,
  ked_enlace TEXT NOT NULL,
  ked_agen VARCHAR(20) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);

-- +goose Down
DROP TABLE ke_dataconex;

DROP TABLE ke_doccti;

DROP TABLE ke_doclmv;

