// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: configuration.sql

package db

import (
	"context"
	"time"
)

const adminGetConfigById = `-- name: AdminGetConfigById :one
select id, cnfg_idconfig, cnfg_clase, cnfg_tipo, cnfg_valnum, cnfg_valsino, cnfg_valtxt, cnfg_lentxt, cnfg_valfch, cnfg_activa, cnfg_etiq, cnfg_ttip, user_id, created_at, updated_at, deleted_at
from ke_wcnf_conf
where id = ?
`

func (q *Queries) AdminGetConfigById(ctx context.Context, id string) (KeWcnfConf, error) {
	row := q.db.QueryRowContext(ctx, adminGetConfigById, id)
	var i KeWcnfConf
	err := row.Scan(
		&i.ID,
		&i.CnfgIdconfig,
		&i.CnfgClase,
		&i.CnfgTipo,
		&i.CnfgValnum,
		&i.CnfgValsino,
		&i.CnfgValtxt,
		&i.CnfgLentxt,
		&i.CnfgValfch,
		&i.CnfgActiva,
		&i.CnfgEtiq,
		&i.CnfgTtip,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const adminGetConfigs = `-- name: AdminGetConfigs :many
select id, cnfg_idconfig, cnfg_clase, cnfg_tipo, cnfg_valnum, cnfg_valsino, cnfg_valtxt, cnfg_lentxt, cnfg_valfch, cnfg_activa, cnfg_etiq, cnfg_ttip, user_id, created_at, updated_at, deleted_at
from ke_wcnf_conf
`

func (q *Queries) AdminGetConfigs(ctx context.Context) ([]KeWcnfConf, error) {
	rows, err := q.db.QueryContext(ctx, adminGetConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeWcnfConf
	for rows.Next() {
		var i KeWcnfConf
		if err := rows.Scan(
			&i.ID,
			&i.CnfgIdconfig,
			&i.CnfgClase,
			&i.CnfgTipo,
			&i.CnfgValnum,
			&i.CnfgValsino,
			&i.CnfgValtxt,
			&i.CnfgLentxt,
			&i.CnfgValfch,
			&i.CnfgActiva,
			&i.CnfgEtiq,
			&i.CnfgTtip,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createConfig = `-- name: CreateConfig :exec
INSERT INTO ke_wcnf_conf (
    id,
    cnfg_idconfig,
    cnfg_clase,
    cnfg_tipo,
    cnfg_valnum,
    cnfg_valsino,
    cnfg_valtxt,
    cnfg_lentxt,
    cnfg_valfch,
    cnfg_activa,
    cnfg_etiq,
    cnfg_ttip,
    user_id,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
`

type CreateConfigParams struct {
	ID           string
	CnfgIdconfig string
	CnfgClase    string
	CnfgTipo     string
	CnfgValnum   string
	CnfgValsino  bool
	CnfgValtxt   string
	CnfgLentxt   int16
	CnfgValfch   time.Time
	CnfgActiva   bool
	CnfgEtiq     string
	CnfgTtip     string
	UserID       string
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) error {
	_, err := q.db.ExecContext(ctx, createConfig,
		arg.ID,
		arg.CnfgIdconfig,
		arg.CnfgClase,
		arg.CnfgTipo,
		arg.CnfgValnum,
		arg.CnfgValsino,
		arg.CnfgValtxt,
		arg.CnfgLentxt,
		arg.CnfgValfch,
		arg.CnfgActiva,
		arg.CnfgEtiq,
		arg.CnfgTtip,
		arg.UserID,
	)
	return err
}

const getConfigByUser = `-- name: GetConfigByUser :many
select id, cnfg_idconfig, cnfg_clase, cnfg_tipo, cnfg_valnum, cnfg_valsino, cnfg_valtxt, cnfg_lentxt, cnfg_valfch, cnfg_activa, cnfg_etiq, cnfg_ttip, user_id, created_at, updated_at, deleted_at
from ke_wcnf_conf
where user_id = ? and deleted_at is null
`

func (q *Queries) GetConfigByUser(ctx context.Context, userID string) ([]KeWcnfConf, error) {
	rows, err := q.db.QueryContext(ctx, getConfigByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeWcnfConf
	for rows.Next() {
		var i KeWcnfConf
		if err := rows.Scan(
			&i.ID,
			&i.CnfgIdconfig,
			&i.CnfgClase,
			&i.CnfgTipo,
			&i.CnfgValnum,
			&i.CnfgValsino,
			&i.CnfgValtxt,
			&i.CnfgLentxt,
			&i.CnfgValfch,
			&i.CnfgActiva,
			&i.CnfgEtiq,
			&i.CnfgTtip,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserConfigById = `-- name: GetUserConfigById :one
select id, cnfg_idconfig, cnfg_clase, cnfg_tipo, cnfg_valnum, cnfg_valsino, cnfg_valtxt, cnfg_lentxt, cnfg_valfch, cnfg_activa, cnfg_etiq, cnfg_ttip, user_id, created_at, updated_at, deleted_at
from ke_wcnf_conf
where id = ? and user_id = ? and deleted_at is null
`

type GetUserConfigByIdParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetUserConfigById(ctx context.Context, arg GetUserConfigByIdParams) (KeWcnfConf, error) {
	row := q.db.QueryRowContext(ctx, getUserConfigById, arg.ID, arg.UserID)
	var i KeWcnfConf
	err := row.Scan(
		&i.ID,
		&i.CnfgIdconfig,
		&i.CnfgClase,
		&i.CnfgTipo,
		&i.CnfgValnum,
		&i.CnfgValsino,
		&i.CnfgValtxt,
		&i.CnfgLentxt,
		&i.CnfgValfch,
		&i.CnfgActiva,
		&i.CnfgEtiq,
		&i.CnfgTtip,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteConfig = `-- name: SoftDeleteConfig :exec
UPDATE ke_wcnf_conf
SET deleted_at = NOW()
WHERE id = ?
`

func (q *Queries) SoftDeleteConfig(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteConfig, id)
	return err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE ke_wcnf_conf
SET cnfg_clase = ?,
    cnfg_tipo = ?,
    cnfg_valnum = ?,
    cnfg_valsino = ?,
    cnfg_valtxt = ?,
    cnfg_lentxt = ?,
    cnfg_valfch = ?,
    cnfg_activa = ?,
    cnfg_etiq = ?,
    cnfg_ttip = ?,
    updated_at = NOW() 
WHERE id = ?
`

type UpdateConfigParams struct {
	CnfgClase   string
	CnfgTipo    string
	CnfgValnum  string
	CnfgValsino bool
	CnfgValtxt  string
	CnfgLentxt  int16
	CnfgValfch  time.Time
	CnfgActiva  bool
	CnfgEtiq    string
	CnfgTtip    string
	ID          string
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig,
		arg.CnfgClase,
		arg.CnfgTipo,
		arg.CnfgValnum,
		arg.CnfgValsino,
		arg.CnfgValtxt,
		arg.CnfgLentxt,
		arg.CnfgValfch,
		arg.CnfgActiva,
		arg.CnfgEtiq,
		arg.CnfgTtip,
		arg.ID,
	)
	return err
}
