// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type KeDataconex struct {
	KedCodigo string
	KedNombre string
	KedStatus int32
	KedEnlace string
	KedAgen   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
