// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Articulo struct {
	Codigo       string
	Grupo        int32
	Subgrupo     int32
	Nombre       string
	Referencia   string
	Marca        string
	Unidad       string
	Existencia   int32
	Precio1      string
	Precio2      string
	Precio3      string
	Precio4      string
	Precio5      string
	Precio6      string
	Precio7      string
	Discont      bool
	VtaMax       int32
	VtaMin       int32
	Dctotope     string
	Enpreventa   bool
	Comprometido int32
	VtaMinenx    int32
	VtaSolofac   bool
	VtaSolone    bool
	Codbarras    string
	Detalles     string
	Cantbulto    int32
	CostoProm    string
	Util1        string
	Util2        string
	Util3        string
	Fchultcomp   time.Time
	Qtyultcomp   int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type Cliempre struct {
	Codigo          string
	Nombre          string
	Direccion       sql.NullString
	Telefonos       sql.NullString
	Perscont        sql.NullString
	Vendedor        sql.NullString
	Contribespecial bool
	Status          int16
	Sector          sql.NullInt32
	Subcodigo       int32
	Precio          int16
	Email           string
	KneActiva       bool
	KneMtomin       string
	Noemifac        bool
	Noeminota       bool
	Fchultvta       time.Time
	Mtoultvta       string
	Prcdpagdia      string
	Promdiasp       string
	Riesgocrd       string
	Cantdocs        int32
	Totmtodocs      string
	Prommtodoc      string
	Diasultvta      string
	Promdiasvta     string
	Limcred         string
	Fchcrea         time.Time
	Dolarflete      bool
	Nodolarflete    bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type DatosUsuario struct {
	UserCodigo    string
	Nombre        sql.NullString
	Telefonos     sql.NullString
	TelefonoMovil sql.NullString
	Direccion     sql.NullString
	Sector        sql.NullInt32
	Subcodigo     int32
	Supervpor     string
	Comisiones    bool
	UltSinc       time.Time
	Version       string
}

type Grupo struct {
	Codigo    int32
	Nombre    sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type KeDataconex struct {
	KedCodigo string
	KedNombre string
	KedStatus bool
	KedEnlace string
	KedAgen   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type KeDoccti struct {
	Agencia        string
	Tipodoc        string
	Documento      string
	Tipodocv       string
	Codcliente     string
	Nombrecli      string
	Contribesp     bool
	RutaParme      bool
	Tipoprecio     string
	Emision        time.Time
	Recepcion      time.Time
	Vence          time.Time
	Diascred       string
	Estatusdoc     string
	Dtotneto       string
	Dtotimpuest    string
	Dtotalfinal    string
	Dtotpagos      string
	Dtotdescuen    string
	Dflete         string
	Dtotdev        string
	Dvndmtototal   string
	Dretencion     string
	Dretencioniva  string
	Vendedor       string
	Codcoord       string
	Aceptadev      bool
	KtiNegesp      bool
	Bsiva          string
	Bsflete        string
	Bsretencion    string
	Bsretencioniva string
	Tasadoc        string
	Mtodcto        string
	Fchvencedcto   time.Time
	Tienedcto      bool
	Cbsret         string
	Cdret          string
	Cbsretiva      string
	Cdretiva       string
	Cbsrparme      string
	Cdrparme       string
	Cbsretflete    string
	Cdretflete     string
	Bsmtoiva       string
	Bsmtofte       string
	RetmunMto      string
	Dolarflete     bool
	Bsretflete     string
	Dretflete      string
	DretmunMto     string
	Retivaoblig    bool
	Edoentrega     bool
	Dmtoiva        string
	Prcdctoaplic   string
	Montodctodol   string
	Montodctobs    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type KeDoclmv struct {
	Agencia       string
	Tipodoc       string
	Documento     string
	Tipodocv      string
	Grupo         int32
	Subgrupo      int32
	Origen        string
	Codigo        string
	Codhijo       string
	Pid           string
	Nombre        string
	Cantidad      int32
	Cntdevuelt    int32
	Vndcntdevuelt string
	Dvndmtototal  string
	Dpreciofin    string
	Dpreciounit   string
	Dmontoneto    string
	Dmontototal   string
	Timpueprc     string
	Unidevuelt    int32
	Fechadoc      time.Time
	Vendedor      string
	Codcoord      string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type KeEstadc01 struct {
	Codcoord      string
	Nomcoord      string
	Vendedor      string
	Nombrevend    string
	Cntpedidos    int32
	Mtopedidos    string
	Cntfacturas   int32
	Mtofacturas   string
	Metavend      string
	Prcmeta       string
	Cntclientes   int32
	Clivisit      int32
	Prcvisitas    string
	LomMontovtas  string
	LomPrcvtas    string
	LomPrcvisit   string
	RlomMontovtas string
	RlomPrcvtas   string
	RlomPrcvisit  string
	FechaEstad    time.Time
	PpgdolTotneto string
	DevdolTotneto string
	DefdolTotneto string
	Totdolcob     string
	Cntrecl       string
	Mtorecl       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type KeOpmv struct {
	KtiTdoc    string
	KtiNdoc    string
	KtiTipprec string
	KmvCodart  string
	KmvNombre  string
	KmvCant    int32
	KmvArtprec string
	KmvStot    string
	KmvDctolin string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
}

type KeOpti struct {
	KtiNdoc        string
	KtiTdoc        string
	KtiCodcli      string
	KtiNombrecli   string
	KtiCodven      string
	KtiDocsol      string
	KtiCondicion   string
	KtiTipprec     string
	KtiTotneto     string
	KtiStatus      string
	KtiNroped      string
	KtiFchdoc      time.Time
	KtiNegesp      bool
	KePedstatus    string
	Dolarflete     bool
	Complemento    bool
	NroComplemento string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type KeWcnfConf struct {
	CnfgIdconfig string
	CnfgClase    string
	CnfgTipo     string
	CnfgValnum   string
	CnfgValsino  bool
	CnfgValtxt   string
	CnfgLentxt   int16
	CnfgValfch   time.Time
	CnfgActiva   bool
	CnfgEtiq     string
	CnfgTtip     string
	Username     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type Listbanc struct {
	Codbanco  int16
	Nombanco  string
	Cuentanac string
	Inactiva  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Sectore struct {
	Codigo    int32
	Zona      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Subgrupo struct {
	Codigo    int32
	Subcodigo int32
	Nombre    sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Subsectore struct {
	Codigo    int32
	Subcodigo int32
	Subsector string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Usuario struct {
	Codigo       string
	Username     string
	Email        string
	Password     sql.NullString
	Status       string
	Desactivo    bool
	CierreSesion bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
