// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type UsuarioRole string

const (
	UsuarioRoleCliente       UsuarioRole = "cliente"
	UsuarioRoleVendedor      UsuarioRole = "vendedor"
	UsuarioRoleGerente       UsuarioRole = "gerente"
	UsuarioRoleAdministrador UsuarioRole = "administrador"
)

func (e *UsuarioRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsuarioRole(s)
	case string:
		*e = UsuarioRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsuarioRole: %T", src)
	}
	return nil
}

type NullUsuarioRole struct {
	UsuarioRole UsuarioRole
	Valid       bool // Valid is true if UsuarioRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsuarioRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsuarioRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsuarioRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsuarioRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsuarioRole), nil
}

type Articulo struct {
	ID           string
	Codigo       string
	Grupo        int32
	Subgrupo     int32
	Nombre       string
	Referencia   string
	Marca        string
	Unidad       string
	Existencia   int32
	Precio1      string
	Precio2      string
	Precio3      string
	Precio4      string
	Precio5      string
	Precio6      string
	Precio7      string
	Discont      bool
	VtaMax       int32
	VtaMin       int32
	Dctotope     string
	Enpreventa   bool
	Comprometido int32
	VtaMinenx    int32
	VtaSolofac   bool
	VtaSolone    bool
	Codbarras    string
	Detalles     string
	Cantbulto    int32
	CostoProm    string
	Util1        string
	Util2        string
	Util3        string
	Fchultcomp   time.Time
	Qtyultcomp   int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type Cliente struct {
	ID              string
	UserID          sql.NullString
	Codigo          string
	Nombre          string
	Direccion       string
	Telefonos       string
	Perscont        string
	Vendedor        string
	Contribespecial bool
	Status          int16
	Sector          int32
	Subcodigo       int32
	Precio          int16
	Email           string
	KneActiva       bool
	KneMtomin       string
	Noemifac        bool
	Noeminota       bool
	Fchultvta       time.Time
	Mtoultvta       string
	Prcdpagdia      string
	Promdiasp       string
	Riesgocrd       string
	Cantdocs        int32
	Totmtodocs      string
	Prommtodoc      string
	Diasultvta      string
	Promdiasvta     string
	Limcred         string
	Dolarflete      bool
	Nodolarflete    bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type KeDataconex struct {
	ID        string
	KedCodigo string
	KedNombre string
	KedStatus bool
	KedEnlace string
	KedAgen   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type KeDoccti struct {
	ID             string
	Agencia        string
	Tipodoc        string
	Documento      string
	Tipodocv       string
	Codcliente     string
	Nombrecli      string
	Contribesp     bool
	RutaParme      bool
	Tipoprecio     string
	Emision        time.Time
	Recepcion      time.Time
	Vence          time.Time
	Diascred       string
	Estatusdoc     string
	Dtotneto       string
	Dtotimpuest    string
	Dtotalfinal    string
	Dtotpagos      string
	Dtotdescuen    string
	Dflete         string
	Dtotdev        string
	Dvndmtototal   string
	Dretencion     string
	Dretencioniva  string
	Vendedor       string
	Codcoord       string
	Aceptadev      bool
	KtiNegesp      bool
	Bsiva          string
	Bsflete        string
	Bsretencion    string
	Bsretencioniva string
	Tasadoc        string
	Mtodcto        string
	Fchvencedcto   time.Time
	Tienedcto      bool
	Cbsret         string
	Cdret          string
	Cbsretiva      string
	Cdretiva       string
	Cbsrparme      string
	Cdrparme       string
	Cbsretflete    string
	Cdretflete     string
	Bsmtoiva       string
	Bsmtofte       string
	RetmunMto      string
	Dolarflete     bool
	Bsretflete     string
	Dretflete      string
	DretmunMto     string
	Retivaoblig    bool
	Edoentrega     bool
	Dmtoiva        string
	Prcdctoaplic   string
	Montodctodol   string
	Montodctobs    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type KeDoclmv struct {
	DocID         string
	ArticuloID    string
	Agencia       string
	Tipodoc       string
	Documento     string
	Tipodocv      string
	Grupo         int32
	Subgrupo      int32
	Origen        string
	Codigo        string
	Codhijo       string
	Pid           string
	Nombre        string
	Cantidad      int32
	Cntdevuelt    int32
	Vndcntdevuelt string
	Dvndmtototal  string
	Dpreciofin    string
	Dpreciounit   string
	Dmontoneto    string
	Dmontototal   string
	Timpueprc     string
	Unidevuelt    int32
	Fechadoc      time.Time
	Vendedor      string
	Codcoord      string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type KeEstadc01 struct {
	ID            string
	Codcoord      string
	Nomcoord      string
	Vendedor      string
	Nombrevend    string
	Cntpedidos    int32
	Mtopedidos    string
	Cntfacturas   int32
	Mtofacturas   string
	Metavend      string
	Prcmeta       string
	Cntclientes   int32
	Clivisit      int32
	Prcvisitas    string
	LomMontovtas  string
	LomPrcvtas    string
	LomPrcvisit   string
	RlomMontovtas string
	RlomPrcvtas   string
	RlomPrcvisit  string
	FechaEstad    time.Time
	PpgdolTotneto string
	DevdolTotneto string
	DefdolTotneto string
	Totdolcob     string
	Cntrecl       string
	Mtorecl       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type KeNivgcium struct {
	ID          string
	KngCodgcia  string
	KngCodcoord string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type KeOpmv struct {
	PedidoID   string
	ArticuloID string
	KtiTdoc    string
	KtiNdoc    string
	KtiTipprec string
	KmvCodart  string
	KmvNombre  string
	KmvCant    int32
	KmvArtprec string
	KmvStot    string
	KmvDctolin string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
}

type KeOpti struct {
	ID             string
	KtiNdoc        string
	KtiTdoc        string
	KtiCodcli      string
	KtiNombrecli   string
	KtiCodven      string
	KtiDocsol      string
	KtiCondicion   string
	KtiTipprec     string
	KtiTotneto     string
	KtiStatus      string
	KtiNroped      string
	KtiFchdoc      time.Time
	KtiNegesp      bool
	KePedstatus    string
	Dolarflete     bool
	Complemento    bool
	NroComplemento string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type KeWcnfConf struct {
	ID           string
	CnfgIdconfig string
	CnfgClase    string
	CnfgTipo     string
	CnfgValnum   string
	CnfgValsino  bool
	CnfgValtxt   string
	CnfgLentxt   int16
	CnfgValfch   time.Time
	CnfgActiva   bool
	CnfgEtiq     string
	CnfgTtip     string
	UserID       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type Usuario struct {
	ID        string
	Username  string
	Password  string
	Role      UsuarioRole
	Desactivo bool
	UltSinc   time.Time
	Version   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Vendedor struct {
	ID            string
	UserID        sql.NullString
	Codigo        string
	Nombre        string
	Telefono1     string
	Telefono2     string
	TelefonoMovil string
	Status        int16
	Supervpor     string
	Sector        int32
	Subcodigo     int32
	Email         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}
