// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order_lines.sql

package db

import (
	"context"
)

const createOrderLine = `-- name: CreateOrderLine :exec
insert into closs_order_lines (
    kti_tdoc,
    kti_ndoc,
    kti_tipprec,
    kmv_codart,
    kmv_nombre,
    kmv_cant,
    kmv_artprec,
    kmv_stot,
    kmv_dctolin,
    created_at,
    updated_at
)
values (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateOrderLineParams struct {
	KtiTdoc    string
	KtiNdoc    string
	KtiTipprec string
	KmvCodart  string
	KmvNombre  string
	KmvCant    int64
	KmvArtprec float64
	KmvStot    float64
	KmvDctolin float64
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateOrderLine(ctx context.Context, arg CreateOrderLineParams) error {
	_, err := q.db.ExecContext(ctx, createOrderLine,
		arg.KtiTdoc,
		arg.KtiNdoc,
		arg.KtiTipprec,
		arg.KmvCodart,
		arg.KmvNombre,
		arg.KmvCant,
		arg.KmvArtprec,
		arg.KmvStot,
		arg.KmvDctolin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateOrderLine = `-- name: UpdateOrderLine :exec
update closs_order_lines set kti_tdoc = ?,
    kti_tipprec = ?,
    kmv_nombre = ?,
    kmv_cant = ?,
    kmv_artprec = ?,
    kmv_stot = ?,
    kmv_dctolin = ?,
    updated_at = ?
WHERE kti_ndoc = ? and kmv_codart = ?
`

type UpdateOrderLineParams struct {
	KtiTdoc    string
	KtiTipprec string
	KmvNombre  string
	KmvCant    int64
	KmvArtprec float64
	KmvStot    float64
	KmvDctolin float64
	UpdatedAt  string
	KtiNdoc    string
	KmvCodart  string
}

func (q *Queries) UpdateOrderLine(ctx context.Context, arg UpdateOrderLineParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderLine,
		arg.KtiTdoc,
		arg.KtiTipprec,
		arg.KmvNombre,
		arg.KmvCant,
		arg.KmvArtprec,
		arg.KmvStot,
		arg.KmvDctolin,
		arg.UpdatedAt,
		arg.KtiNdoc,
		arg.KmvCodart,
	)
	return err
}
