// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
;

INSERT  INTO closs_session(
    token,
    user_id
)
VALUES (?, ?)
RETURNING token, user_id
`

type CreateSessionParams struct {
	Token  string
	UserID string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (ClossSession, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.UserID)
	var i ClossSession
	err := row.Scan(&i.Token, &i.UserID)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
delete from closs_session
where user_id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, userID)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
;

delete from closs_session
where token = ?
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByToken, token)
	return err
}

const getTokenById = `-- name: GetTokenById :one
select token, user_id
from closs_session
where user_id = ?
`

func (q *Queries) GetTokenById(ctx context.Context, userID string) (ClossSession, error) {
	row := q.db.QueryRowContext(ctx, getTokenById, userID)
	var i ClossSession
	err := row.Scan(&i.Token, &i.UserID)
	return i, err
}

const getTokenByToken = `-- name: GetTokenByToken :one
;

select token, user_id
from closs_session
where token = ?
`

func (q *Queries) GetTokenByToken(ctx context.Context, token string) (ClossSession, error) {
	row := q.db.QueryRowContext(ctx, getTokenByToken, token)
	var i ClossSession
	err := row.Scan(&i.Token, &i.UserID)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE closs_session SET
    token = ?
WHERE user_id = ?
RETURNING token, user_id
`

type UpdateSessionParams struct {
	Token  string
	UserID string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (ClossSession, error) {
	row := q.db.QueryRowContext(ctx, updateSession, arg.Token, arg.UserID)
	var i ClossSession
	err := row.Scan(&i.Token, &i.UserID)
	return i, err
}
